- name: Install software packages
  hosts: all
  become: true
  tasks:
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - tcpdump
        - mailx
      when: "'proxy' in group_names"
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - lsof
        - mailx
      when: "'database' in group_names"
        