- name: Create a new primary partition with a size of 800MB
  parted:
    device: /dev/sdb
    number: 1
    state: present
    part_start: "100MB"
    part_end: "900MB"
- name: Install lvm2 package
  yum:
    name: lvm2
    state: present
- name: Create physical volume and add it to volume group
  lvg:
    vg: vg_database
    pvs: /dev/sdb1
    state: present
- name: Create logical volume
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512m
    state: present
- name: Create XFS file system
  filesystem:
    fstype: xfs
    dev: "/dev/vg_database/lv_mysql"
- name: Ensure /mnt/mysql_backups directory exists
  file:
    path: /mnt/mysql_backups
    state: directory
    mode: '0755'
- name: Mount the logical volume permanently
  mount:
    path: /mnt/mysql_backups
    src: "/dev/vg_database/lv_mysql"
    fstype: xfs
    state: mounted
    opts: defaults
- name: Install the package
  yum:
    name: mysql-community-server
    state: present
- name: Allow incoming traffic on MySQL port TCP 3306
  firewalld:
    port: 3306/tcp
    state: enabled
    permanent: yes
- name: Template a file to /etc/file.conf
  template:
    src: my.cnf.j2
    dest: /etc/my.conf
    owner: automation
    group: automation
    mode: '0644'
- name: Enable the service on boot
  systemd:
    name: mysqld
    enabled: yes
    state: started
- name: Run MySQL login command
  shell: mysql -uroot -pYourRootPassword -e "your_query_here"
  ignore_errors: yes
- name: Read MySQL temporary password from log file
  shell: "grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'"
  register: mysql_temp_password
  changed_when: false
  failed_when: mysql_temp_password.rc != 0
- name: Print temp password
  debug:
    msg: "{{mysql_temp_password.stdout}}"
- name: Install MySQL-python package
  yum:
    name: MySQL-python
    state: present
- name: Execute SQL query to change authentication plugin
  community.mysql.mysql_query:
    login_user: root
    login_password: your_mysql_root_password
    query: "ALTER USER 'root'@'localhost' IDENTIFIED WITH {{mysql_temp_password.stdout}} BY 'test123';"
