- name: Install httpd and config incoming traffic ports
  hosts: catfood_webservers:bighead_webservers
  become: true
  tasks:
  - name: Install the httpd package
    yum:
      name: httpd
      state: present
  - name: Enable httpd service on boot
    systemd:
      name: httpd
      enabled: yes
      state: started
  - name: Allow all incoming traffic on HTTP port TCP 80 and 443
    firewalld:
      port: "{{ item }}"
      state: enabled
      permanent: yes
    loop:
    - 80/tcp
    - 443/tcp
  - name: Template a file to /var/www/html/index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: vagrant
      group: vagrant
